### ISSUE TITLE
Input fields lose focus

### ISSUE THREAD

**Issue by didi-moritz** [willhaben/ppp#7]
When typing into an input fields it seems that after some seconds the focus is lost und you cannot type characters anymore. You have to select the input field again, but after some seconds the focus is lost again.

**Comment by fabb** [comment]
My first guess was a missing `key` for the items, but you already fixed that here https://github.com/sigsegvat/ppp/pull/1
So what could it be? I took a look at what elements reload when the focus is lost, and it seems the problem is higher up: the whole `<div>` which is the child of the `<div id="__next">` gets reloaded. Or looking at the React debug, the whole `<NoSsr>` container gets replaced. Maybe a `key` is missing somewhere there.

**Comment by fabb** [comment]
Hah, gotcha: #10
